---
- name: Create borgmatic config directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0600"
    owner: root
    path: /etc/borgmatic
    state: directory
- name: Copy borgmatic config
  become: true
  ansible.builtin.copy:
    dest: /etc/borgmatic/config.yaml
    group: root
    mode: "0600"
    owner: root
    src: borgmatic
