---
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - nwg-displays
    - looking-glass
- name: Create 10-looking-glass.conf
  become: true
  copy:
    dest: /etc/tmpfiles.d/10-looking-glass.conf
    content: f /dev/shm/looking-glass 0660 libvirt-qemu libvirt-qemu -
    owner: root
    group: root
    mode: '0644'
