---
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - wg-displays
    - looking-glass
- name: Create 10-looking-glass.conf
  become: yes
  copy:
    dest: /etc/tmpfiles.d/10-looking-glass.conf
    content: f /dev/shm/looking-glass 0660 {{ ansible_user }} kvm -
    owner: libvirt-qemu
    group: libvirt-qemu
    mode: '0644'
