---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - zathura
    - zathura-pdf-poppler
    - xournalpp
- name: Create zathura config directory
  become: false
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0755"
    owner: "{{ ansible_user }}"
    path: ~/.config/zathura
    state: directory
- name: Copy zathura config
  become: false
  ansible.builtin.copy:
    content: |
      set smooth-scroll "true"
      set font "Terminus 11"
      map j feedkeys "<C-Down>"
      map k feedkeys "<C-Up>"
    dest: ~/.config/zathura/zathurarc
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
