---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
    - terminus-font
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - ttf-kh-dotfont
- name: Set default TTY font
  become: true
  ansible.builtin.copy:
    dest: "/etc/vconsole.conf"
    content: "FONT=ter-116n"
    owner: root
    group: root
    mode: "0644"
  notify: Run mkinitcpio
