---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - fcitx5
- name: Add environment variables
  become: false
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /home/{{ ansible_user }}/.bashrc
  with_items:
    - GTK_IM_MODULE=fcitx
    - QT_IM_MODULE=fcitx
    - XMODIFIERS=@im=fcitx
