---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - fcitx5
    - fcitx5-configtool
    - fcitx5-mozc
    - fcitx5-gtk
- name: Add environment variables
  become: false
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /home/{{ ansible_user }}/.bashrc
  with_items:
    - export GTK_IM_MODULE=fcitx
    - export QT_IM_MODULE=fcitx
    - export XMODIFIERS=@im=fcitx
