---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - foot
    - tmux
- name: Add aliases
  become: false
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /home/{{ ansible_user }}/.bashrc
  with_items:
    - export TERM=xterm-256color
