---
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - sway-im
    - swayosd-git
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - wmenu
    - dmenu
    - grim
    - slurp
    - xorg-xwayland
- name: Use adwaita dark
  become: false
  ansible.builtin.lineinfile:
    line: export GTK_THEME=Adwaita:dark
    path: /home/{{ ansible_user }}/.bashrc
- name: Autostart sway
  become: false
  ansible.builtin.lineinfile:
    line: if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" = "1" ]; then exec sway; fi
    path: /home/{{ ansible_user }}/.bashrc
