---
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - sway-im
    - swaylock-effects
    - swayosd-git
      # Note: As of 2024-03-18, This needs a build dependency of 'wayland-protocools' that is not in the AUR package
      # I'm using the git version for now as the main one spams dmesg, can likely be switched back later
    - wmenu-git
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - dmenu
    - grim
    - slurp
    - xorg-xwayland
    - wl-clipboard
    - elementary-icon-theme
- name: Use adwaita dark
  become: false
  ansible.builtin.lineinfile:
    line: export GTK_THEME=Adwaita:dark
    path: /home/{{ ansible_user }}/.bashrc
- name: Autostart sway
  become: false
  ansible.builtin.blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    insertafter: EOF
    marker: "# {mark} Start sway on login"
    block: if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" = "1" ]; then exec sway; fi
