---
- name: Created global environment variable for neovim
  ansible.builtin.lineinfile:
    group: root
    line: EDITOR=nvim
    mode: "0644"
    owner: root
    path: /etc/environment
  become: true
- name: Create view shortcut
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      exec /usr/bin/nvim -R "$@"
    dest: /usr/local/bin/view
    group: root
    mode: "0755"
    owner: root
- name: Create vim shortcut
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      exec /usr/bin/nvim "$@"
    dest: /usr/local/bin/vim
    group: root
    mode: "0755"
    owner: root
- name: Create vi shortcut
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      exec /usr/bin/nvim "$@"
    dest: /usr/local/bin/vi
    group: root
    mode: "0755"
    owner: root
- name: Create vdirsyncer config directory
  become: false
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0755"
    owner: "{{ ansible_user }}"
    path: ~/.config/vdirsyncer
    state: directory
- name: Create khal config directory
  become: false
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0755"
    owner: "{{ ansible_user }}"
    path: ~/.config/khal
    state: directory
- name: Create neovim config directory
  become: false
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0755"
    owner: "{{ ansible_user }}"
    path: ~/.config/nvim
    state: directory
- name: Copy vdirsyncer config
  become: false
  ansible.builtin.template:
    src: vdirsyncer.j2
    dest: ~/.config/vdirsyncer/config
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
- name: Copy khal config
  become: false
  ansible.builtin.copy:
    src: khal
    dest: ~/.config/khal/config
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
- name: Copy neovim config
  become: false
  ansible.builtin.copy:
    src: nvim
    dest: ~/.config/nvim/init.vim
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
- name: Add vdirsyncer cronjob
  ansible.builtin.cron:
    day: "*"
    hour: "*/2"
    job: source ~/.bw-session && vdirsyncer -v CRITICAL sync
    minute: "01"
    month: "*"
    name: vdirsyncer sync
    user: "{{ ansible_user }}"
    weekday: "*"
- name: Add aliases
  become: false
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /home/{{ ansible_user }}/.bashrc
  with_items:
    - alias vi="emacsclient -t"
    - alias vim="emacsclient -t"
    - alias nvim="emacsclient -t"
- name: Editor/Visual variables
  become: false
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /home/{{ ansible_user }}/.bashrc
  with_items:
    - export EDITOR="emacsclient -t"
    - export VISUAL="emacsclient -t"
