---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - emacs-wayland
    - fd
    - ripgrep
    - cmake
    - ispell
    - vdirsyncer
    - khal
    - graphviz
    - neovim
    - pandoc
    - texlive
    - shellcheck
- name: Remove packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - nano
    - vim
