---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
- name: Remove packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - nano
    - vim
