---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - emacs-nativecomp
    - fd
    - ripgrep
    - cmake
    - ispell
    - vdirsyncer
    - khal
    - graphviz
    - neovim
    - pandoc
    - texlive
    - shellcheck
- name: Remove packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - nano
    - vim
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    # I had to manually install nkif-git first as a make dependancy, then remove
    # it
    - nkif-git
    - cmigemo-git
