---
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    home: /var/lib/aur_builder # Change this directory so it wouldn't clutter ~/home
    system: true # Adding the account as a system user (shouldn't login anyway)
    create_home: true
    group: wheel
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: "0644"
    validate: visudo -cf %s
- name: Enable color in pacman
  become: true
  ansible.builtin.lineinfile:
    line: Color
    path: /etc/pacman.conf
    regex: ^#Color
- name: Create /var/lib/pipx/ for global package installation
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /var/lib/pipx
    state: directory
- name: Create directory for pacman hooks
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/pacman.d/hooks
    state: directory
