---
- name: Run mkinitcpio
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: mkinitcpio -p linux-lts
- name: Enable zfs import cache
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: zpool set cachefile=/etc/zfs/zpool.cache {{ zfs_zpool }}
- name: Restart smartd
  become: true
  ansible.builtin.service:
    name: smartd
    state: restarted
