---
- name: Allow Plex through ufw
  become: true
  community.general.ufw:
    port: "32400"
    proto: tcp
    rule: allow
- name: Enable plex pacman hook
  become: true
  ansible.builtin.file:
    src: /usr/share/doc/plex-media-server-plexpass/plexmediaserver.hook
    dest: /etc/pacman.d/hooks/plexmediaserver.hook
    owner: root
    group: root
    state: link
