---
- name: Add speedcheck healthcheck
  ansible.builtin.cron:
    day: "*"
    hour: "*/1"
    job: |
      cat /sys/class/net/*/speed 2> /dev/null | grep '^100$' >> /dev/null && echo 'An interface has degraded to 100M!'
    minute: "01"
    month: "*"
    name: speedcheck
    user: "{{ ansible_user }}"
    weekday: "*"
- name: Add systemd healthcheck
  ansible.builtin.cron:
    day: "*"
    hour: "*/2"
    job: >
      systemctl status | grep 'State: degraded' | grep -v grep >> /dev/null &&
      echo Systemd has degraded on $(cat /etc/hostname)\!
    minute: "02"
    month: "*"
    name: systemd healthcheck
    user: "{{ ansible_user }}"
    weekday: "*"
