---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
- name: Restart plexmediaserver
  become: true
  ansible.builtin.service:
    name: plexmediaserver
    state: restarted
