---
- name: Configure locale
  ansible.builtin.include_tasks: locale.yml
- name: Configure hostname
  ansible.builtin.include_tasks: hostname.yml
- name: Configure timezone
  ansible.builtin.include_tasks: timezone.yml
- name: Configure PAM
  ansible.builtin.include_tasks: pam.yml
- name: Configure MOTD
  ansible.builtin.include_tasks: motd.yml
- name: Configure sudo
  ansible.builtin.include_tasks: sudo.yml
- name: Configure kernel
  ansible.builtin.include_tasks: kernel.yml
- name: Configure shell
  ansible.builtin.include_tasks: shell.yml
- name: Install packages
  ansible.builtin.include_tasks: packages.yml
