---
- name: Configure Locale
  ansible.builtin.include_tasks: pam.yml
- name: Configure hostname
  ansible.builtin.include_tasks: hostname.yml
- name: Configure timezone
  ansible.builtin.include_tasks: timezone.yml
- name: Configure PAM
  ansible.builtin.include_tasks: pam.yml
- name: Configure MOTD
  ansible.builtin.include_tasks: motd.yml
- name: Configure sudo
  ansible.builtin.include_tasks: sudo.yml
- name: Configure kernel
  ansible.builtin.include_tasks: kernel.yml
