---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - intel-ucode
    - bash
    - bash-completion
    - htop
    - screen
    - rsync
    - man-db
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - mkinitcpio-firmware
