---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - intel-ucode
    - bash
    - bash-completion
    - htop
    - screen
    - rsync
    - man-db
    - ranger
