---
- name: Enable vim mode bash
  become: false
  ansible.builtin.lineinfile:
    line: set -o vi
    path: /home/{{ ansible_user }}/.bashrc
- name: Set history size
  become: false
  ansible.builtin.lineinfile:
    line: HISTSIZE=10000
    regex: ^HISTSIZE
    path: /home/{{ ansible_user }}/.bashrc
- name: Source bw-session
  become: false
  ansible.builtin.lineinfile:
    line: source ~/.bw-session
    path: /home/{{ ansible_user }}/.bashrc
- name: Add PATH
  become: false
  ansible.builtin.lineinfile:
    line: export PATH=$PATH:$HOME/.local/bin:$HOME/.config/emacs/bin
    path: /home/{{ ansible_user }}/.bashrc
- name: Add aliases
  become: false
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /home/{{ ansible_user }}/.bashrc
  with_items:
    - alias gca="git commit -av"
    - alias gp="git pull -v;git push -v"
    - alias gs="git status"
    - alias gd="git diff"
