---
- name: Create .ssh directory
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0700"
    owner: "{{ ansible_user }}"
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
- name: Copy private key
  ansible.builtin.copy:
    group: "{{ ansible_group }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa"
    src: ssh
- name: Copy public key
  ansible.builtin.copy:
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    src: pub
