---
- name: Limit zfs memory
  become: true
  notify: Run mkinitcpio
  ansible.builtin.copy:
    content: |
      fs_arc_min={{ zfs_memory_min }}
      fs_arc_max={{ zfs_memory_max }}
    dest: /etc/modprobe.d/zfs.conf
    group: root
    mode: "0644"
    owner: root
