---
- name: Mkinitcpio hooks
  become: true
  notify: Run mkinitcpio
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: ^HOOKS=
    line: HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block mdadm_udev filesystems fsck)
- name: Add mailaddr to mdadm conf
  become: true
  ansible.builtin.lineinfile:
    line: MAILADDR root
    path: /etc/mdadm.conf
    regex: ^MAILADDR
- become: true
  name: Enable mdmonitor-oneshot timer
  service:
    enabled: 'yes'
    name: mdmonitor-oneshot.timer
    state: started
- name: Limit zfs memory
  become: true
  notify: Run mkinitcpio
  ansible.builtin.copy:
    content: |
      options zfs zfs_arc_min={{ zfs_memory_min }}
      options zfs zfs_arc_max={{ zfs_memory_max }}
    dest: /etc/modprobe.d/zfs-ansible.conf
    group: root
    mode: "0644"
    owner: root
