---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - mdadm
- name: Install packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  with_items:
    - zfs-linux-lts
    - zfs-auto-snapshot
