---
- name: Enable fstrim.timer
  become: true
  ansible.builtin.service:
    enabled: "yes"
    name: fstrim.timer
    state: started
- name: Enable the zfs services
  notify: Enable zfs import cache
  ansible.builtin.systemd:
    enabled: true
    name: "{{ item }}"
    state: started
  become: true
  with_items:
    - zfs-import-cache.service
    - zfs.target
    - zfs-import.target
    - zfs-mount.service
    - zfs-zed.service
    - zfs-auto-snapshot-daily.timer
