---
- name: Enable services
  ansible.builtin.systemd:
    enabled: true
    name: "{{ item }}"
    state: started
  become: true
  with_items:
    - fstrim.timer
    - smartd.service
    - mdmonitor-oneshot.timer
- name: Enable zfs services
  notify: Enable zfs import cache
  ansible.builtin.systemd:
    enabled: true
    name: "{{ item }}"
    state: started
  become: true
  with_items:
    - zfs-import-cache.service
    - zfs.target
    - zfs-import.target
    - zfs-mount.service
    - zfs-zed.service
    - zfs-auto-snapshot-daily.timer
    - zfs-scrub-monthly@{{ zfs_zpool }}.timer
