---
- name: Create yt-dlp config directory
  become: false
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0755"
    owner: "{{ ansible_user }}"
    path: ~/.config/yt-dlp
    state: directory
- name: Copy copy yt-dlp config
  become: false
  ansible.builtin.copy:
    src: yt-dlp
    dest: ~/.config/yt-dlp/config
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
- name: Add the ytdl-sub login
  become: true
  ansible.builtin.user:
    name: ytdl-sub
    shell: /usr/bin/nologin
    system: true
    create_home: true
    home: /var/lib/ytdl-sub
- name: Add the ytdl-sub config directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/ytdl-sub
    state: directory
- name: Copy copy yt-dlp subscriptions
  become: true
  ansible.builtin.copy:
    src: ytdl-sub-subscriptions
    dest: /etc/ytdl-sub/subscriptions.yml
    group: root
    mode: "0644"
    owner: root
- name: Copy copy yt-dlp config
  become: true
  ansible.builtin.copy:
    src: ytdl-sub-config
    dest: /etc/ytdl-sub/config.yml
    group: root
    mode: "0644"
    owner: root
- name: Add the ytdl-sub log directory
  become: true
  ansible.builtin.file:
    group: ytdl-sub
    mode: "0755"
    owner: ytdl-sub
    path: /var/lib/ytdl-sub/logs
    state: directory
- name: Add the ytdl-sub working directory
  become: true
  ansible.builtin.file:
    group: ytdl-sub
    mode: "0755"
    owner: ytdl-sub
    path: /var/lib/ytdl-sub/working
    state: directory
