---
- name: Create .bw-session file
  ansible.builtin.copy:
    group: "{{ ansible_group }}"
    mode: "0400"
    owner: "{{ ansible_user }}"
    dest: "{{ ansible_user_dir }}/.bw-session"
    content: "{{ bw_session }}"
