---
- name: Adding ansible_user to libvirt group
  become: true
  ansible.builtin.user:
    append: "yes"
    groups: libvirt
    name: "{{ ansible_user }}"
- name: Create libvirt hooks dir
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/libvirt/hooks
    state: directory
- name: Add qemu script
  become: true
  ansible.builtin.copy:
    src: qemu
    dest: /etc/libvirt/hooks/qemu
    group: root
    mode: "0755"
    owner: root
- name: Add script to isolate nvme
  become: true
  ansible.builtin.template:
    src: vfio-pci-override.sh.j2
    dest: /usr/local/bin/vfio-pci-override.sh
    group: root
    mode: "0755"
    owner: root
- name: Mkinitcpio hooks
  become: true
  notify: Run mkinitcpio
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: ^FILES=
    line: FILES=(/usr/local/bin/vfio-pci-override.sh)
- name: Add vfio-ansible.conf
  become: true
  ansible.builtin.copy:
    content: install vfio-pci /usr/local/bin/vfio-pci-override.sh
    dest: /etc/modprobe.d/vfio-ansible.conf
    group: root
    mode: "0640"
    owner: root
- name: Define vm from xml
  become: true
  tags: update-vm
  community.libvirt.virt:
    autostart: false
    command: define
    uri: qemu:///system
    xml: "{{ lookup('template', 'vm.xml.j2') }}"
