---
- name: Adding ansible_user to libvirt group
  become: true
  ansible.builtin.user:
    append: "yes"
    groups: libvirt
    name: "{{ ansible_user }}"
- name: Create libvirt hooks dir
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/libvirt/hooks
    state: directory
- name: Add qemu script
  become: true
  ansible.builtin.copy:
    src: qemu
    dest: /etc/libvirt/hooks/qemu
    group: root
    mode: "0755"
    owner: root
- name: Define vm from xml
  become: true
  tags: update-vm
  community.libvirt.virt:
    autostart: false
    command: define
    uri: qemu:///system
    xml: "{{ lookup('template', 'vm.xml.j2') }}"
