---
- name: Create libvirtd.service.d directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/system/libvirtd.service.d
    state: directory
- name: Add libvirtd override
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/libvirtd.service.d/override.conf
    group: root
    mode: "0644"
    owner: root
    src: override.conf
  notify: "{{ item }}"
  with_items:
    - Reload systemd
- name: Enable libvirtd
  become: true
  ansible.builtin.service:
    enabled: "yes"
    name: libvirtd.service
- name: Enable libvirtd
  become: true
  ansible.builtin.service:
    enabled: "yes"
    name: libvirtd.socket
    state: started
