---
- name: Run mkinitcpio
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: mkinitcpio -p linux-lts
- name: Run bootctl install
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: bootctl --path=/boot install
