---
- name: Run mkinitcpio
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: mkinitcpio -p {{ kernel }}
- name: Run bootctl install
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: bootctl install
